#!/bin/bash

# Get the currently playing song using playerctl
info=$(playerctl metadata --format '{{artist}} - {{title}}' 2>/dev/null)

# If nothing is playing or there's an error
if [ -z "$info" ]; then
    echo "No song playing"
else
    echo "$info"
fi
