#!/bin/bash

# Start background services and apps
#nm-applet &
mako &
# poweralertd &
# wayland-pipewire-idle-inhibit &
swww-daemon &
systemctl --user start hyprpolkitagent.service
hypridle &
# blueman-applet &
# rog-control-center &
waybar &
bluetoothctl power off &
