#!/bin/bash

# Start background services and apps
nm-applet &
swww-daemon &
# poweralertd &
# wayland-pipewire-idle-inhibit &
swaync &
systemctl --user start hyprpolkitagent.service
hypridle &
# blueman-applet &
# rog-control-center &
waybar &
bluetoothctl power off &

# Restore gamemode toggle
sh ~/.config/hypr/scripts/restore-gamemode.sh

#gamode watcher
sh .config/hypr/scripts/gamemode-watcher.sh 

# Reset hyprsunset state
if pgrep -x hyprsunset > /dev/null; then
    pkill hyprsunset
else
    (hyprsunset & sleep 0.1 && pkill hyprsunset)
fi

# Clear caffeine flag on session start
rm -f ~/.cache/caffeinated_active
